package com.cloudwick.kvstore;

import com.cloudwick.kvstore.grpc.KVStoreServiceGrpc;
import com.cloudwick.kvstore.grpc.PutRequest;
import com.cloudwick.kvstore.grpc.PutResponse;
import com.cloudwick.kvstore.grpc.GetRequest;
import com.cloudwick.kvstore.grpc.GetResponse;
import com.cloudwick.kvstore.grpc.DeleteRequest;
import com.cloudwick.kvstore.grpc.DeleteResponse;
import com.cloudwick.kvstore.grpc.VoteRequest;
import com.cloudwick.kvstore.grpc.VoteResponse;
import com.cloudwick.kvstore.grpc.AppendRequest;
import com.cloudwick.kvstore.grpc.AppendResponse;
import com.cloudwick.kvstore.grpc.LogEntry;
import com.google.protobuf.ByteString;
import io.grpc.stub.StreamObserver;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

/**
 * KVStoreServiceImpl is the "Brain" of our database. 
 * It extends a class auto-generated by gRPC, which allows this class to directly receive 
 * network messages from clients and other nodes.
 * 
 * Think of this class as the manager that glues together the RAM (HashMap), 
 * the Hard Drive (WriteAheadLog), and the Cluster (RaftNode).
 */
public class KVStoreServiceImpl extends KVStoreServiceGrpc.KVStoreServiceImplBase {

    // The actual "Database" where data lives in memory. 
    // We use ConcurrentHashMap because multiple network threads might try to read/write at the exact same time.
    private final ConcurrentHashMap<String, ByteString> store = new ConcurrentHashMap<>();
    
    // The "Hard Drive" ledger. We use this to survive crashes.
    private final WriteAheadLog wal;
    
    // The shared in-memory log of all operations
    private final List<LogEntry> logList;
    
    // Tracks what we have actually applied to our RAM HashMap
    private int lastAppliedToStore = -1;
    
    // The "Cluster Manager". We use this to talk to other servers and handle elections.
    private final RaftNode raftNode;

    /**
     * Constructor: Called once when the server starts up.
     */
    public KVStoreServiceImpl(WriteAheadLog wal, List<LogEntry> logList, RaftNode raftNode) throws IOException {
        this.wal = wal;
        this.logList = logList;
        this.raftNode = raftNode;
        
        System.out.println("Rebuilding state from Write-Ahead Log...");
        
        // CRASH RECOVERY: The very first thing we do before accepting any network traffic
        // is iterate through the loaded logList and replay every action.
        // This perfectly rebuilds the HashMap exactly as it was right before the server crashed.
        for (LogEntry entry : logList) {
            if (entry.getOp() == LogEntry.Operation.PUT) {
                store.put(entry.getKey(), entry.getValue());
            } else if (entry.getOp() == LogEntry.Operation.DELETE) {
                store.remove(entry.getKey());
            }
            lastAppliedToStore++;
        }
        System.out.println("Restored " + logList.size() + " operations from WAL.");
        
        // TWO-PHASE COMMIT CALLBACK
        // RaftNode will call this whenever the cluster reaches consensus on a new log index
        this.raftNode.setApplyCallback(commitIndex -> {
            while (lastAppliedToStore < commitIndex) {
                lastAppliedToStore++;
                LogEntry entry = logList.get(lastAppliedToStore);
                if (entry.getOp() == LogEntry.Operation.PUT) {
                    store.put(entry.getKey(), entry.getValue());
                } else if (entry.getOp() == LogEntry.Operation.DELETE) {
                    store.remove(entry.getKey());
                }
                System.out.println("Node " + raftNode.getNodeId() + " APPLIED log index " + lastAppliedToStore + " to RAM.");
            }
        });
    }

    // ========================================================================
    // --- Client API Methods (Called by users of the database) ---
    // ========================================================================

    /**
     * Called when a client wants to save data. (e.g. PUT "username" = "Cloudwick")
     */
    @Override
    public void put(PutRequest request, StreamObserver<PutResponse> responseObserver) {
        
        // RAFT RULE: Only the Leader is allowed to accept writes!
        // If a client accidentally sends a PUT to a Follower, we instantly reject it.
        if (raftNode.getRole() != RaftNode.Role.LEADER) {
            String leaderHint = (raftNode.getCurrentLeaderId() != null) 
                ? "Leader is " + raftNode.getCurrentLeaderId() 
                : "Leader is unknown";
                
            responseObserver.onError(io.grpc.Status.UNAVAILABLE
                    .withDescription("Not the leader. " + leaderHint)
                    .asRuntimeException());
            return;
        }

        String key = request.getKey();
        ByteString value = request.getValue();
        
        try {
            // 1. Package the user's data into a LogEntry object
            LogEntry entry = LogEntry.newBuilder()
                    .setOp(LogEntry.Operation.PUT)
                    .setKey(key)
                    .setValue(value)
                    .setTerm(raftNode.getCurrentTerm())
                    .build();
                    
            // 2. Write to our own Hard Drive and RAM log FIRST.
            wal.append(entry); 
            logList.add(entry);
            
            // 3. Broadcast this data to all the Followers in the cluster.
            // This method pauses (blocks) until a MAJORITY of followers reply "Success".
            boolean replicated = raftNode.replicateLog();
            
            // 4. If a majority didn't reply (e.g. network partition), we fail the request.
            if (!replicated) {
                responseObserver.onError(io.grpc.Status.UNAVAILABLE
                        .withDescription("Failed to replicate to a majority of the cluster")
                        .asRuntimeException());
                return;
            }
            
            // 5. SUCCESS! The data is safe on a majority of hard drives. 
            // Our applyCallback has already automatically inserted it into the store!
            
            // Increment our Prometheus observability metric.
            MetricsExporter.PUT_REQUESTS.labels(String.valueOf(raftNode.getNodeId())).inc();
            System.out.println("Node " + raftNode.getNodeId() + " (LEADER) processed PUT key: " + key);
            
            // 6. Tell the user "Success!"
            PutResponse response = PutResponse.newBuilder().setSuccess(true).build();
            responseObserver.onNext(response);
            responseObserver.onCompleted(); // Closes the network connection
            
        } catch (IOException e) {
            // If our own hard drive fails, tell the client it was an internal error.
            responseObserver.onError(io.grpc.Status.INTERNAL
                    .withDescription("Failed to append to WAL")
                    .withCause(e)
                    .asRuntimeException());
        }
    }

    /**
     * Called when a client wants to read data. (e.g. GET "username")
     */
    @Override
    public void get(GetRequest request, StreamObserver<GetResponse> responseObserver) {
        
        // Notice we do NOT check if we are the Leader here. 
        // In this basic design, we allow Followers to serve reads to make the system faster.
        // However, this means a client might get "stale" data if they read from a slow Follower!
        String key = request.getKey();
        
        // Grab the data instantly from RAM (incredibly fast)
        ByteString value = store.get(key);
        
        System.out.println("Node " + raftNode.getNodeId() + " GET key: " + key);
        MetricsExporter.GET_REQUESTS.labels(String.valueOf(raftNode.getNodeId())).inc();
        
        GetResponse.Builder responseBuilder = GetResponse.newBuilder();
        if (value != null) {
            responseBuilder.setFound(true).setValue(value);
        } else {
            responseBuilder.setFound(false);
        }
        
        // Send the data back to the client
        responseObserver.onNext(responseBuilder.build());
        responseObserver.onCompleted();
    }

    /**
     * Called when a client wants to delete data. 
     * The logic here is identical to PUT, because deleting data is still modifying the database.
     */
    @Override
    public void delete(DeleteRequest request, StreamObserver<DeleteResponse> responseObserver) {
        // Only Leader can delete
        if (raftNode.getRole() != RaftNode.Role.LEADER) {
            String leaderHint = (raftNode.getCurrentLeaderId() != null) 
                ? "Leader is " + raftNode.getCurrentLeaderId() 
                : "Leader is unknown";
                
            responseObserver.onError(io.grpc.Status.UNAVAILABLE
                    .withDescription("Not the leader. " + leaderHint)
                    .asRuntimeException());
            return;
        }

        String key = request.getKey();
        
        try {
            // Create a DELETE log entry
            LogEntry entry = LogEntry.newBuilder()
                    .setOp(LogEntry.Operation.DELETE)
                    .setKey(key)
                    .setTerm(raftNode.getCurrentTerm())
                    .build();
                    
            // Save to hard drive and log
            wal.append(entry);
            logList.add(entry);
            
            // Replicate to followers
            boolean replicated = raftNode.replicateLog();
            if (!replicated) {
                responseObserver.onError(io.grpc.Status.UNAVAILABLE
                        .withDescription("Failed to replicate DELETE to a majority of the cluster")
                        .asRuntimeException());
                return;
            }
            
            // Remove from RAM (now handled by applyCallback)
            System.out.println("Node " + raftNode.getNodeId() + " (LEADER) processed DELETE key: " + key);
            
            DeleteResponse response = DeleteResponse.newBuilder()
                    .setSuccess(true)
                    .build();
                    
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        } catch (IOException e) {
            responseObserver.onError(io.grpc.Status.INTERNAL
                    .withDescription("Failed to append to WAL")
                    .withCause(e)
                    .asRuntimeException());
        }
    }

    // ========================================================================
    // --- Raft RPC Implementations (Called by OTHER nodes in the cluster) ---
    // ========================================================================

    /**
     * Called when another node starts an election and asks us for our vote.
     */
    @Override
    public void requestVote(VoteRequest request, StreamObserver<VoteResponse> responseObserver) {
        // We delegate the complex voting logic to RaftNode.java
        VoteResponse response = raftNode.handleRequestVote(request);
        
        // Send our YES or NO vote back to the candidate over the network
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    /**
     * Called when the LEADER wants to send us a Heartbeat OR new data to replicate.
     */
    @Override
    public void appendEntries(AppendRequest request, StreamObserver<AppendResponse> responseObserver) {
        // First, RaftNode checks the Term to make sure this is a legitimate Leader
        AppendResponse response = raftNode.handleAppendEntries(request);
        
        // If it is a legitimate Leader (success == true) AND they actually sent data (entriesCount > 0)
        if (response.getSuccess() && request.getEntriesCount() > 0) {
            
            try {
                // TRUNCATION LOGIC (Healing): 
                // If the leader is overwriting our old logs, we must truncate our local log and WAL.
                int startIndex = request.getPrevLogIndex() + 1;
                if (startIndex < logList.size()) {
                    System.out.println("Node " + raftNode.getNodeId() + " truncating logs from index " + startIndex);
                    logList.subList(startIndex, logList.size()).clear();
                    
                    // Note: In a production database, we would cleanly rewrite or truncate the actual file.
                    // For this simple project, we rewrite the entire WAL to drop the old entries.
                    wal.rewrite(logList);
                }
                
                // Loop through all the data the Leader sent us
                for (LogEntry entry : request.getEntriesList()) {
                    // 1. Save it to our local hard drive (WAL) and log
                    wal.append(entry);
                    logList.add(entry);
                    
                    // Note: We DO NOT apply it to the RAM HashMap here!
                    // We must wait for the Leader's next heartbeat to update the commitIndex.
                    
                    System.out.println("Node " + raftNode.getNodeId() + " (FOLLOWER) replicated " + entry.getOp() + " key: " + entry.getKey() + " to WAL.");
                }
            } catch (IOException e) {
                System.err.println("Failed to write replicated log to WAL");
                e.printStackTrace();
            }
        }
        
        // Tell the Leader we successfully processed the message, and return our current last index
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }
}
